"""creacion_relacion_usuario_tarea

Revision ID: 5ffb6b78b46d
Revises: 483d5c1f9e5a
Create Date: 2026-01-03 14:59:52.968194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffb6b78b46d'
down_revision = '483d5c1f9e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('tasks_name_key'), type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('tasks_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
